# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
      time: "12:00"
    # Raise all npm pull requests with an assignee
    assignees:
      - jorana
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 25
    assignees:
      - jorana
  # Maintain the requirements requirements folder
  - package-ecosystem: "pip"
    directory: "/extra_requirements"
    schedule:
      # Check for updates to requirements every week
      interval: "weekly"
      time: "12:00"
    open-pull-requests-limit: 25
    assignees:
      - jorana
