# Config for writing documentation

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: extra_requirements/requirements-base.txt
    - requirements: extra_requirements/requirements-tests.txt
    - requirements: extra_requirements/requirements-docs.txt
    - method: setuptools
      path: .

formats:
  - pdf
  - epub
