ignore:
  - data/*
  - tests/*

# See https://docs.sourcery.ai/refactorings/lift-duplicated-conditional/
# Excluded use-named-expression -> It's for clear code that this is useful
refactor:
  skip:
    inline-immediately-returned-variable
    use-named-expression
    use-dictionary-union

github:
  request_review: owner
