ignore:
  - data/*
  - tests/*

# See https://docs.sourcery.ai/refactorings/lift-duplicated-conditional/
refactor:
  skip:
  - inline-immediately-returned-variable
  - use-named-expression  # This is for code clarity

github:
  request_review: owner