ignore:
  - data/*
  - tests/*

# See https://docs.sourcery.ai/refactorings/lift-duplicated-conditional/
refactor:
  skip:
    - inline-immediately-returned-variable
    # This is for code clarity
    - use-named-expression

github:
  request_review: owner