on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v2 # https://github.com/marketplace/actions/setup-miniconda
      with:
        python-version: 3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: dddm
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install conda stuff on linux
      run: |
        bash .github/scripts/install_on_linux.sh
    - name: Install python dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Install other stuff
      run: |
          pip install pytest hypothesis flake8 pytest-cov coveralls
          pip install git+https://github.com/TimoRoth/coveralls-python.git
    - name: Install DirectDmTargets
      run: python setup.py develop
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        export LD_LIBRARY_PATH=/home/runner/work/DirectDmTargets/DirectDmTargets/MultiNest/lib
        coverage run --source=DirectDmTargets setup.py test
        coveralls --service=github
