on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage
    - name: Setup python
      uses: actions/setup-python@v2 # https://github.com/marketplace/actions/setup-miniconda
      with:
        python-version: 3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: dddm
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install conda stuff on linux
      run: |
        bash .github/scripts/install_on_linux.sh
    - name: Install python dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Install other stuff
      run: pip install pytest hypothesis flake8 pytest-cov
    - name: Install DirectDmTargets
      run: python setup.py develop
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}