# Test package every time

name: Pytest

# Controls when the action will run.

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2.2.2 # https://github.com/marketplace/actions/setup-miniconda
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-activate-base: true
          activate-environment: dddm
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Make installation linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          bash .github/scripts/install_on_linux.sh
      - name: Make installation windows
        if: matrix.os == 'windows-latest'
        run: |
          cmd .github/scripts/install_on_windows.sh
      - name: Install other stuff
        run: |
          pip install -r extra_requirements/requirements-tests.txt
          python setup.py develop
      - name: Build coverage file (windows)
        if: matrix.os == 'windows-latest'
        run: |
            pytest --verbose
      - name: Test package (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/DirectDmTargets/DirectDmTargets/MultiNest/lib
          pytest --verbose
      - name: goodbye
        run: echo goodbye
